{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 24,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "      peakDemandTimes  meteredValues\n",
      "0 2023-11-28 00:00:00          0.000\n",
      "1 2023-11-28 01:00:00         13.499\n",
      "2 2023-11-28 02:00:00          6.647\n",
      "3 2023-11-28 03:00:00          7.073\n"
     ]
    },
    {
     "ename": "KeyError",
     "evalue": "Timestamp('2023-11-28 00:00:00')",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mKeyError\u001b[0m                                  Traceback (most recent call last)",
      "File \u001b[0;32m~/.local/lib/python3.9/site-packages/pandas/core/indexes/base.py:3790\u001b[0m, in \u001b[0;36mIndex.get_loc\u001b[0;34m(self, key)\u001b[0m\n\u001b[1;32m   3789\u001b[0m \u001b[39mtry\u001b[39;00m:\n\u001b[0;32m-> 3790\u001b[0m     \u001b[39mreturn\u001b[39;00m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m_engine\u001b[39m.\u001b[39;49mget_loc(casted_key)\n\u001b[1;32m   3791\u001b[0m \u001b[39mexcept\u001b[39;00m \u001b[39mKeyError\u001b[39;00m \u001b[39mas\u001b[39;00m err:\n",
      "File \u001b[0;32mindex.pyx:152\u001b[0m, in \u001b[0;36mpandas._libs.index.IndexEngine.get_loc\u001b[0;34m()\u001b[0m\n",
      "File \u001b[0;32mindex.pyx:181\u001b[0m, in \u001b[0;36mpandas._libs.index.IndexEngine.get_loc\u001b[0;34m()\u001b[0m\n",
      "File \u001b[0;32mpandas/_libs/hashtable_class_helper.pxi:7080\u001b[0m, in \u001b[0;36mpandas._libs.hashtable.PyObjectHashTable.get_item\u001b[0;34m()\u001b[0m\n",
      "File \u001b[0;32mpandas/_libs/hashtable_class_helper.pxi:7088\u001b[0m, in \u001b[0;36mpandas._libs.hashtable.PyObjectHashTable.get_item\u001b[0;34m()\u001b[0m\n",
      "\u001b[0;31mKeyError\u001b[0m: Timestamp('2023-11-28 00:00:00')",
      "\nThe above exception was the direct cause of the following exception:\n",
      "\u001b[0;31mKeyError\u001b[0m                                  Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[24], line 30\u001b[0m\n\u001b[1;32m     28\u001b[0m \u001b[39m# Print peakDemandTimes, meteredValues, and result\u001b[39;00m\n\u001b[1;32m     29\u001b[0m \u001b[39mfor\u001b[39;00m hour, metered_value \u001b[39min\u001b[39;00m \u001b[39mzip\u001b[39m(df_updated[\u001b[39m'\u001b[39m\u001b[39mpeakDemandTimes\u001b[39m\u001b[39m'\u001b[39m], df_updated[\u001b[39m'\u001b[39m\u001b[39mmeteredValues\u001b[39m\u001b[39m'\u001b[39m]):\n\u001b[0;32m---> 30\u001b[0m     \u001b[39mprint\u001b[39m(\u001b[39mf\u001b[39m\u001b[39m\"\u001b[39m\u001b[39m{\u001b[39;00mhour\u001b[39m.\u001b[39mstrftime(\u001b[39m'\u001b[39m\u001b[39m%\u001b[39m\u001b[39mY-\u001b[39m\u001b[39m%\u001b[39m\u001b[39mm-\u001b[39m\u001b[39m%d\u001b[39;00m\u001b[39m \u001b[39m\u001b[39m%\u001b[39m\u001b[39mH:\u001b[39m\u001b[39m%\u001b[39m\u001b[39mM:\u001b[39m\u001b[39m%\u001b[39m\u001b[39mS\u001b[39m\u001b[39m'\u001b[39m)\u001b[39m}\u001b[39;00m\u001b[39m | \u001b[39m\u001b[39m{\u001b[39;00mmetered_value\u001b[39m}\u001b[39;00m\u001b[39m | \u001b[39m\u001b[39m{\u001b[39;00mresult_updated[hour]\u001b[39m}\u001b[39;00m\u001b[39m\"\u001b[39m)\n",
      "File \u001b[0;32m~/.local/lib/python3.9/site-packages/pandas/core/frame.py:3896\u001b[0m, in \u001b[0;36mDataFrame.__getitem__\u001b[0;34m(self, key)\u001b[0m\n\u001b[1;32m   3894\u001b[0m \u001b[39mif\u001b[39;00m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mcolumns\u001b[39m.\u001b[39mnlevels \u001b[39m>\u001b[39m \u001b[39m1\u001b[39m:\n\u001b[1;32m   3895\u001b[0m     \u001b[39mreturn\u001b[39;00m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_getitem_multilevel(key)\n\u001b[0;32m-> 3896\u001b[0m indexer \u001b[39m=\u001b[39m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mcolumns\u001b[39m.\u001b[39;49mget_loc(key)\n\u001b[1;32m   3897\u001b[0m \u001b[39mif\u001b[39;00m is_integer(indexer):\n\u001b[1;32m   3898\u001b[0m     indexer \u001b[39m=\u001b[39m [indexer]\n",
      "File \u001b[0;32m~/.local/lib/python3.9/site-packages/pandas/core/indexes/base.py:3797\u001b[0m, in \u001b[0;36mIndex.get_loc\u001b[0;34m(self, key)\u001b[0m\n\u001b[1;32m   3792\u001b[0m     \u001b[39mif\u001b[39;00m \u001b[39misinstance\u001b[39m(casted_key, \u001b[39mslice\u001b[39m) \u001b[39mor\u001b[39;00m (\n\u001b[1;32m   3793\u001b[0m         \u001b[39misinstance\u001b[39m(casted_key, abc\u001b[39m.\u001b[39mIterable)\n\u001b[1;32m   3794\u001b[0m         \u001b[39mand\u001b[39;00m \u001b[39many\u001b[39m(\u001b[39misinstance\u001b[39m(x, \u001b[39mslice\u001b[39m) \u001b[39mfor\u001b[39;00m x \u001b[39min\u001b[39;00m casted_key)\n\u001b[1;32m   3795\u001b[0m     ):\n\u001b[1;32m   3796\u001b[0m         \u001b[39mraise\u001b[39;00m InvalidIndexError(key)\n\u001b[0;32m-> 3797\u001b[0m     \u001b[39mraise\u001b[39;00m \u001b[39mKeyError\u001b[39;00m(key) \u001b[39mfrom\u001b[39;00m \u001b[39merr\u001b[39;00m\n\u001b[1;32m   3798\u001b[0m \u001b[39mexcept\u001b[39;00m \u001b[39mTypeError\u001b[39;00m:\n\u001b[1;32m   3799\u001b[0m     \u001b[39m# If we have a listlike key, _check_indexing_error will raise\u001b[39;00m\n\u001b[1;32m   3800\u001b[0m     \u001b[39m#  InvalidIndexError. Otherwise we fall through and re-raise\u001b[39;00m\n\u001b[1;32m   3801\u001b[0m     \u001b[39m#  the TypeError.\u001b[39;00m\n\u001b[1;32m   3802\u001b[0m     \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_check_indexing_error(key)\n",
      "\u001b[0;31mKeyError\u001b[0m: Timestamp('2023-11-28 00:00:00')"
     ]
    }
   ],
   "source": [
    "import pandas as pd\n",
    "\n",
    "\n",
    "# Updated data\n",
    "updated_data = {\n",
    "    'meteredValues': [0.0, 6.639, 0.0, 3.785, 3.075, 0.0, 6.647, 0.0, 0.0, 5.351, 0.0, 0.0, 1.722],\n",
    "    'peakDemandTimes': [\n",
    "        '2023-11-28 00:00:00', '2023-11-28 00:15:00', '2023-11-28 00:30:00', '2023-11-28 00:45:00',\n",
    "        '2023-11-28 01:00:00', '2023-11-28 01:15:00', '2023-11-28 01:30:00',\n",
    "        '2023-11-28 01:45:00', '2023-11-28 02:00:00', '2023-11-28 02:15:00',\n",
    "        '2023-11-28 02:30:00', '2023-11-28 02:45:00', '2023-11-28 03:00:00',\n",
    "    ]\n",
    "}\n",
    "\n",
    "df_updated = pd.DataFrame(updated_data)\n",
    "\n",
    "# Convert 'peakDemandTimes' to datetime\n",
    "df_updated['peakDemandTimes'] = pd.to_datetime(df_updated['peakDemandTimes'])\n",
    "\n",
    "# Round 'peakDemandTimes' to the nearest hour\n",
    "df_updated['peakDemandTimes'] = df_updated['peakDemandTimes'].dt.ceil('H')\n",
    "\n",
    "# Group by hourly and sum 'meteredValues'\n",
    "result_updated = df_updated.groupby(df_updated['peakDemandTimes'])['meteredValues'].sum()()\n",
    "\n",
    "print(result_updated)\n",
    "\n",
    "# Print peakDemandTimes, meteredValues, and result\n",
    "for hour, metered_value in zip(df_updated['peakDemandTimes'], df_updated['meteredValues']):\n",
    "    print(f\"{hour.strftime('%Y-%m-%d %H:%M:%S')} | {metered_value} | {result_updated[hour]}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 58,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "{'meteredValues': [0], 'peakDemandTimes': [Timestamp('2023-11-28 00:00:00')]}\n"
     ]
    }
   ],
   "source": [
    "\n",
    "import sys \n",
    "sys.path.append('/home/pi/smart_plug/')\n",
    "import os\n",
    "import pandas as pd\n",
    "import sqlite3\n",
    "from datetime import datetime, timedelta\n",
    "from database.db_manager import DatabaseManager\n",
    "import datetime\n",
    " \n",
    "from external_services.awattar_services import AwattarServices\n",
    "from external_services.smartmeter_services import SmartMeterServices\n",
    "from database.db_manager import DatabaseManager\n",
    "from main_services.common_utils import common_utils \n",
    " \n",
    "import pandas as pd\n",
    "import datetime\n",
    "\n",
    "\n",
    "# Datetime\n",
    "# Get the current date\n",
    "current_date = str(datetime.date.today() - datetime.timedelta(days=1))\n",
    "\n",
    "# Combine with the time '00:00:00'\n",
    "combined_datetime = pd.to_datetime(current_date + ' 00:00:00')\n",
    "\n",
    "\n",
    "# Default dataset\n",
    "default_data = {'meteredValues': [0],\n",
    "    'peakDemandTimes': [combined_datetime]}\n",
    "\n",
    "print(default_data)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "\n",
    "\n",
    "import sys \n",
    "sys.path.append('/home/pi/smart_plug/')\n",
    "import os\n",
    "import pandas as pd\n",
    "import sqlite3\n",
    "from datetime import datetime, timedelta\n",
    "from database.db_manager import DatabaseManager\n",
    " \n",
    "\n",
    "# Get the current datetime\n",
    "current_datetime = datetime.now()\n",
    "\n",
    "# Calculate a datetime that is 30 minutes ago\n",
    "datetime_30_minutes_ago = current_datetime - timedelta(minutes=40)\n",
    "\n",
    "# Calculate a datetime that is 1 hour in the future\n",
    "datetime_1_hour_in_future = current_datetime + timedelta(hours=1)\n",
    "\n",
    "print(\"Current Datetime:\", current_datetime)\n",
    "print(\"Datetime 30 Minutes Ago:\", datetime_30_minutes_ago)\n",
    "print(\"Datetime 1 Hour in Future:\", datetime_1_hour_in_future)\n",
    "\n",
    "db = DatabaseManager()\n",
    "status1 = db.read_relaymode_temp(1)\n",
    "print(status1)\n",
    "\n",
    "status2 = db.read_relaymode_temp(2)\n",
    "print(status2)\n",
    "\n",
    "\n",
    "current_datetime = datetime.now() - timedelta(hours=24)\n",
    "start_of_day = current_datetime.replace(hour=0, minute=0, second=0, microsecond=0)\n",
    "end_of_day = current_datetime.replace(hour=23, minute=59, second=59, microsecond=99)\n",
    "\n",
    "print(start_of_day.strftime('%Y-%m-%d %H:%M:%S.%f'))\n",
    "print(end_of_day.strftime('%Y-%m-%d %H:%M:%S'))\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "\n",
    "\n",
    "import sys \n",
    "sys.path.append('/home/pi/smart_plug/')\n",
    "import os\n",
    "import pandas as pd\n",
    "import sqlite3\n",
    "from datetime import datetime, timedelta\n",
    "from database.db_manager import DatabaseManager\n",
    " \n",
    "\n",
    "current_datetime = datetime.now() - timedelta(hours=24)\n",
    "current_datetime = current_datetime.strftime('%Y-%m-%d %H:%M:%S.%f')\n",
    "\n",
    "print(current_datetime)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "\n",
    "import sys \n",
    "sys.path.append('/home/pi/smart_plug/')\n",
    "import os\n",
    "from main_services.common_utils import common_utils \n",
    "\n",
    "test = 'dataset/'+common_utils.static_awattar_filename\n",
    "\n",
    "print(test)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Current working directory: /home/pi/smart_plug/python_files\n",
      "init called\n",
      "2.6.0\n"
     ]
    },
    {
     "ename": "RuntimeError",
     "evalue": "Working outside of request context.\n\nThis typically means that you attempted to use functionality that needed\nan active HTTP request. Consult the documentation on testing for\ninformation about how to avoid this problem.",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mRuntimeError\u001b[0m                              Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[1], line 79\u001b[0m\n\u001b[1;32m     76\u001b[0m         \u001b[39mreturn\u001b[39;00m send_file(image_data, mimetype\u001b[39m=\u001b[39m\u001b[39m'\u001b[39m\u001b[39mimage/png\u001b[39m\u001b[39m'\u001b[39m)\n\u001b[1;32m     77\u001b[0m     \u001b[39mreturn\u001b[39;00m jsonify({\u001b[39m\"\u001b[39m\u001b[39mstatus\u001b[39m\u001b[39m\"\u001b[39m: \u001b[39m\"\u001b[39m\u001b[39mNo data found\u001b[39m\u001b[39m\"\u001b[39m}), \u001b[39m404\u001b[39m\n\u001b[0;32m---> 79\u001b[0m get_data_as_image()\n",
      "Cell \u001b[0;32mIn[1], line 76\u001b[0m, in \u001b[0;36mget_data_as_image\u001b[0;34m()\u001b[0m\n\u001b[1;32m     74\u001b[0m image_data \u001b[39m=\u001b[39m getLiveRelayStatus()\n\u001b[1;32m     75\u001b[0m \u001b[39mif\u001b[39;00m image_data:\n\u001b[0;32m---> 76\u001b[0m     \u001b[39mreturn\u001b[39;00m send_file(image_data, mimetype\u001b[39m=\u001b[39;49m\u001b[39m'\u001b[39;49m\u001b[39mimage/png\u001b[39;49m\u001b[39m'\u001b[39;49m)\n\u001b[1;32m     77\u001b[0m \u001b[39mreturn\u001b[39;00m jsonify({\u001b[39m\"\u001b[39m\u001b[39mstatus\u001b[39m\u001b[39m\"\u001b[39m: \u001b[39m\"\u001b[39m\u001b[39mNo data found\u001b[39m\u001b[39m\"\u001b[39m}), \u001b[39m404\u001b[39m\n",
      "File \u001b[0;32m~/.local/lib/python3.9/site-packages/flask/helpers.py:507\u001b[0m, in \u001b[0;36msend_file\u001b[0;34m(path_or_file, mimetype, as_attachment, download_name, conditional, etag, last_modified, max_age)\u001b[0m\n\u001b[1;32m    393\u001b[0m \u001b[39mdef\u001b[39;00m \u001b[39msend_file\u001b[39m(\n\u001b[1;32m    394\u001b[0m     path_or_file: os\u001b[39m.\u001b[39mPathLike \u001b[39m|\u001b[39m \u001b[39mstr\u001b[39m \u001b[39m|\u001b[39m t\u001b[39m.\u001b[39mBinaryIO,\n\u001b[1;32m    395\u001b[0m     mimetype: \u001b[39mstr\u001b[39m \u001b[39m|\u001b[39m \u001b[39mNone\u001b[39;00m \u001b[39m=\u001b[39m \u001b[39mNone\u001b[39;00m,\n\u001b[0;32m   (...)\u001b[0m\n\u001b[1;32m    401\u001b[0m     max_age: \u001b[39mNone\u001b[39;00m \u001b[39m|\u001b[39m (\u001b[39mint\u001b[39m \u001b[39m|\u001b[39m t\u001b[39m.\u001b[39mCallable[[\u001b[39mstr\u001b[39m \u001b[39m|\u001b[39m \u001b[39mNone\u001b[39;00m], \u001b[39mint\u001b[39m \u001b[39m|\u001b[39m \u001b[39mNone\u001b[39;00m]) \u001b[39m=\u001b[39m \u001b[39mNone\u001b[39;00m,\n\u001b[1;32m    402\u001b[0m ) \u001b[39m-\u001b[39m\u001b[39m>\u001b[39m Response:\n\u001b[1;32m    403\u001b[0m \u001b[39m    \u001b[39m\u001b[39m\"\"\"Send the contents of a file to the client.\u001b[39;00m\n\u001b[1;32m    404\u001b[0m \n\u001b[1;32m    405\u001b[0m \u001b[39m    The first argument can be a file path or a file-like object. Paths\u001b[39;00m\n\u001b[0;32m   (...)\u001b[0m\n\u001b[1;32m    502\u001b[0m \u001b[39m    .. versionadded:: 0.2\u001b[39;00m\n\u001b[1;32m    503\u001b[0m \u001b[39m    \"\"\"\u001b[39;00m\n\u001b[1;32m    504\u001b[0m     \u001b[39mreturn\u001b[39;00m werkzeug\u001b[39m.\u001b[39mutils\u001b[39m.\u001b[39msend_file(  \u001b[39m# type: ignore[return-value]\u001b[39;00m\n\u001b[1;32m    505\u001b[0m         \u001b[39m*\u001b[39m\u001b[39m*\u001b[39m_prepare_send_file_kwargs(\n\u001b[1;32m    506\u001b[0m             path_or_file\u001b[39m=\u001b[39mpath_or_file,\n\u001b[0;32m--> 507\u001b[0m             environ\u001b[39m=\u001b[39mrequest\u001b[39m.\u001b[39;49menviron,\n\u001b[1;32m    508\u001b[0m             mimetype\u001b[39m=\u001b[39mmimetype,\n\u001b[1;32m    509\u001b[0m             as_attachment\u001b[39m=\u001b[39mas_attachment,\n\u001b[1;32m    510\u001b[0m             download_name\u001b[39m=\u001b[39mdownload_name,\n\u001b[1;32m    511\u001b[0m             conditional\u001b[39m=\u001b[39mconditional,\n\u001b[1;32m    512\u001b[0m             etag\u001b[39m=\u001b[39metag,\n\u001b[1;32m    513\u001b[0m             last_modified\u001b[39m=\u001b[39mlast_modified,\n\u001b[1;32m    514\u001b[0m             max_age\u001b[39m=\u001b[39mmax_age,\n\u001b[1;32m    515\u001b[0m         )\n\u001b[1;32m    516\u001b[0m     )\n",
      "File \u001b[0;32m~/.local/lib/python3.9/site-packages/werkzeug/local.py:311\u001b[0m, in \u001b[0;36m_ProxyLookup.__get__\u001b[0;34m(self, instance, owner)\u001b[0m\n\u001b[1;32m    308\u001b[0m     \u001b[39mreturn\u001b[39;00m \u001b[39mself\u001b[39m\n\u001b[1;32m    310\u001b[0m \u001b[39mtry\u001b[39;00m:\n\u001b[0;32m--> 311\u001b[0m     obj \u001b[39m=\u001b[39m instance\u001b[39m.\u001b[39;49m_get_current_object()\n\u001b[1;32m    312\u001b[0m \u001b[39mexcept\u001b[39;00m \u001b[39mRuntimeError\u001b[39;00m:\n\u001b[1;32m    313\u001b[0m     \u001b[39mif\u001b[39;00m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mfallback \u001b[39mis\u001b[39;00m \u001b[39mNone\u001b[39;00m:\n",
      "File \u001b[0;32m~/.local/lib/python3.9/site-packages/werkzeug/local.py:508\u001b[0m, in \u001b[0;36mLocalProxy.__init__.<locals>._get_current_object\u001b[0;34m()\u001b[0m\n\u001b[1;32m    506\u001b[0m     obj \u001b[39m=\u001b[39m local\u001b[39m.\u001b[39mget()\n\u001b[1;32m    507\u001b[0m \u001b[39mexcept\u001b[39;00m \u001b[39mLookupError\u001b[39;00m:\n\u001b[0;32m--> 508\u001b[0m     \u001b[39mraise\u001b[39;00m \u001b[39mRuntimeError\u001b[39;00m(unbound_message) \u001b[39mfrom\u001b[39;00m \u001b[39mNone\u001b[39;00m\n\u001b[1;32m    510\u001b[0m \u001b[39mreturn\u001b[39;00m get_name(obj)\n",
      "\u001b[0;31mRuntimeError\u001b[0m: Working outside of request context.\n\nThis typically means that you attempted to use functionality that needed\nan active HTTP request. Consult the documentation on testing for\ninformation about how to avoid this problem."
     ]
    }
   ],
   "source": [
    "import sys\n",
    "\n",
    "sys.path.append('/home/pi/smart_plug/')\n",
    "import os\n",
    "import schedule\n",
    "import time\n",
    "from PIL import Image\n",
    "import io\n",
    "\n",
    "import sqlite3\n",
    "from sqlite3 import Error\n",
    "\n",
    "from datetime import datetime\n",
    "\n",
    "from external_services.awattar_services import AwattarServices\n",
    "from pi_controller.relay_controller import RelayControl\n",
    "from external_services.smartmeter_services import SmartMeterServices\n",
    "from database.db_manager import DatabaseManager\n",
    "from main_services.common_utils import common_utils \n",
    "\n",
    "\n",
    "from flask import Flask, jsonify, request, send_file\n",
    "\n",
    "from PIL import Image\n",
    "import io\n",
    "import pandas as pd\n",
    "import matplotlib.pyplot as plt\n",
    "\n",
    "current_dir = os.getcwd()\n",
    "print(\"Current working directory:\", current_dir)\n",
    "\n",
    "app = Flask(__name__)\n",
    "\n",
    "\n",
    "# Helper function to convert data to image\n",
    "def data_to_image(data):\n",
    "    # Assuming data is a binary representation of an image\n",
    "    image = Image.open(io.BytesIO(data))\n",
    "    return image\n",
    "\n",
    "\n",
    "def getLiveRelayStatus():\n",
    "    try:\n",
    "            # Connect to the SQLite database\n",
    "            db = DatabaseManager()\n",
    "            \n",
    "            conn = sqlite3.connect(\"/home/pi/smart_plug/database/pythonsqlite.db\")\n",
    "            cursor = conn.cursor()\n",
    "\n",
    "            df = pd.read_sql_query(\"SELECT start_timestamp, end_timestamp, marketprice, unit, relaynumber FROM automaterelay\", conn)\n",
    "\n",
    "            # Check if the DataFrame is not empty\n",
    "            if not df.empty:\n",
    "                # Plot the DataFrame as a table\n",
    "                fig, ax = plt.subplots(figsize=(8, 6))\n",
    "                ax.axis('tight')\n",
    "                ax.axis('off')\n",
    "                table = ax.table(cellText=df.values, colLabels=df.columns, cellLoc='center', loc='center')\n",
    "                image_file = io.BytesIO()\n",
    "                plt.savefig(image_file, format='png', bbox_inches='tight')\n",
    "                image_file.seek(0)\n",
    "                plt.close()\n",
    "                return image_file\n",
    "            return None\n",
    "               \n",
    "    except Exception as e:\n",
    "        print(f\"An error occurred: {e}\")\n",
    "        return jsonify({\"status\": \"Error\"}), 500\n",
    "\n",
    "    finally:\n",
    "        conn.close()\n",
    "\n",
    "def get_data_as_image():\n",
    "    image_data = getLiveRelayStatus()\n",
    "    if image_data:\n",
    "        return send_file(image_data, mimetype='image/png')\n",
    "    return jsonify({\"status\": \"No data found\"}), 404\n",
    "\n",
    "get_data_as_image()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.2"
  },
  "orig_nbformat": 4
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
